Repository fossa-app/UI, pull requests merged in 2024-10, with the labels that each got.

#689 Update CURL package
  Dockerfile
Labels: maintenance

#688 update: Enhance auth flow
  src/AxiosInterceptor.tsx
  src/layout/Header/Header.tsx
  src/pages/Callback.tsx
  src/pages/Login.tsx
  src/shared/helpers/index.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/helpers/user-manager.helpers.ts
  src/store/features/authSlice.ts
Labels: enhancement

#690 update: Update prettier
  .eslintrc.json
  .prettierrc
  public/index.html
  src/App.tsx
  src/AxiosInterceptor.tsx
  src/__mocks__/store.ts
  src/__mocks__/tests/Header.test.tsx
  src/index.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Footer/components/Environment.tsx
  src/layout/Header/Header.tsx
  src/layout/Header/components/UserMenu/UserMenu.tsx
  src/pages/Company.tsx
  src/pages/Login.tsx
  src/reportWebVitals.ts
  src/shared/helpers/user-manager.helpers.ts
  src/shared/models/user.ts
  src/store/features/appConfigSlice.ts
  src/store/features/authSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/licenseSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#692 feat: Create company as admin
  src/App.tsx
  src/__mocks__/tests/Login.test.tsx
  src/pages/Branches.tsx
  src/pages/Company.tsx
  src/pages/Employee.tsx
  src/pages/Setup.tsx
  src/shared/constants/index.ts
  src/shared/constants/roles.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/models/user.ts
  src/store/features/authSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#693 update: Change theme colors
  src/App.tsx
  src/core/theme.config.ts
  src/pages/Setup.tsx
  src/shared/constants/colors.ts
Labels: enhancement

#694 feat: Create branch
  src/App.tsx
  src/AxiosInterceptor.tsx
  src/pages/Branches.tsx
  src/pages/Company.tsx
  src/pages/Setup/Branches.tsx
  src/pages/Setup/Company.tsx
  src/pages/Setup/Employee.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/shared/components/Snackbar.tsx
  src/shared/constants/urls.ts
  src/shared/models/branch.ts
  src/shared/models/common.ts
  src/shared/models/error.ts
  src/shared/models/index.ts
  src/shared/models/response.ts
  src/store/features/authSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#695 update: Refactor
  src/App.tsx
  src/AxiosInterceptor.tsx
  src/__mocks__/store.ts
  src/layout/Footer/Footer.tsx
  src/layout/Header/Header.tsx
  src/pages/Callback.tsx
  src/pages/Login.tsx
  src/pages/Protected.tsx
  src/pages/Setup/Branches.tsx
  src/pages/Setup/Company.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/routes/router.tsx
  src/shared/components/Loader.tsx
  src/shared/components/Snackbar.tsx
  src/shared/constants/configs.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/helpers/user-manager.helpers.ts
Labels: enhancement

#697 feat: Migrate to createBrowserRouter
  src/App.tsx
  src/AxiosInterceptor.tsx
  src/ClientLoader.tsx
  src/RootLayout.tsx
  src/index.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Header/Header.tsx
  src/pages/Dashboard.tsx
  src/pages/Login.tsx
  src/pages/Protected.tsx
  src/pages/Setup/Branches.tsx
  src/pages/Setup/Company.tsx
  src/pages/Setup/Employee.tsx
  src/pages/Setup/Setup.tsx
  src/routes/router.tsx
  src/shared/components/Loader.tsx
  src/shared/components/Snackbar.tsx
  src/shared/constants/configs.ts
  src/shared/constants/urls.ts
Labels: enhancement

#700 update: Move shared components to UI folder
  src/AxiosInterceptor.tsx
  src/ClientLoader.tsx
  src/components/UI/Loader.tsx
  src/components/UI/Logo.tsx
  src/components/UI/Snackbar.tsx
  src/layout/Header/Header.tsx
  src/layout/RootLayout.tsx
  src/pages/Callback.tsx
  src/pages/Protected.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/routes/router.tsx
Labels: enhancement

#701 feat: Add general error handling
  src/AxiosInterceptor.tsx
  src/core/axios.config.ts
  src/shared/constants/configs.ts
  src/store/features/authSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/licenseSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#703 feat: Create employee & refactoring
  package-lock.json
  package.json
  src/AxiosInterceptor.tsx
  src/ClientLoader.tsx
  src/__mocks__/tests/Footer.test.tsx
  src/components/UI/Logo.tsx
  src/components/UI/Snackbar.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Footer/components/Environment.tsx
  src/layout/Header/components/UserMenu/UserMenu.tsx
  src/pages/Callback.tsx
  src/pages/Root.tsx
  src/pages/Setup/Branches.tsx
  src/pages/Setup/Company.tsx
  src/pages/Setup/Employee.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/routes/router.tsx
  src/shared/configs/axios.config.ts
  src/shared/configs/theme.config.ts
  src/shared/constants/configs.ts
  src/shared/models/employee.ts
  src/shared/models/index.ts
  src/shared/models/setup.ts
  src/store/features/authSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/licenseSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#704 feat: Improve company
  src/ClientLoader.tsx
  src/__mocks__/store.ts
  src/__mocks__/tests/Footer.test.tsx
  src/__mocks__/tests/Header.test.tsx
  src/__mocks__/tests/Login.test.tsx
  src/layout/Content.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Footer/components/License.tsx
  src/layout/Header/Header.tsx
  src/pages/Login.tsx
  src/pages/Setup/Branches.tsx
  src/pages/Setup/Company.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/shared/models/branch.ts
  src/shared/models/company.ts
  src/shared/models/employee.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#705 update: Refactor setup flow
  src/AxiosInterceptor.tsx
  src/layout/Footer/components/License.tsx
  src/pages/Protected.tsx
  src/pages/Setup/Branches.tsx
  src/pages/Setup/Company.tsx
  src/pages/Setup/Employee.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/shared/configs/axios.config.ts
  src/shared/constants/configs.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/models/branch.ts
  src/shared/models/common.ts
  src/shared/models/company.ts
  src/shared/models/employee.ts
  src/store/features/authSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/licenseSlice.ts
  src/store/features/setupSlice.ts
  src/store/index.ts
Labels: enhancement

#707 feat: Enhance navigation
  src/AxiosInterceptor.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Header/Header.tsx
  src/pages/Callback.tsx
  src/pages/NotFound.tsx
  src/pages/Protected.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/routes/router.tsx
  src/shared/constants/configs.ts
  src/shared/constants/routes.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/models/route.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#709 feat: Init manage page
  src/__mocks__/store.ts
  src/__mocks__/tests/Header.test.tsx
  src/layout/Header/Header.tsx
  src/pages/Callback.tsx
  src/pages/Manage/Manage.tsx
  src/pages/Protected.tsx
  src/pages/Setup/Setup.tsx
  src/routes/router.tsx
  src/shared/constants/routes.ts
  src/shared/models/route.ts
Labels: enhancement

#710 feat: Init generic search
  src/__mocks__/tests/Header.test.tsx
  src/components/Search/Search.tsx
  src/components/Search/StyledSearch.tsx
  src/layout/Header/Header.tsx
  src/layout/Header/components/ThemeSwitch.tsx
  src/layout/Header/components/UserMenu.tsx
  src/shared/constants/index.ts
  src/shared/constants/search-contexts.ts
  src/shared/helpers/url.helpers.ts
Labels: enhancement

#711 feat: Create title components
  src/AxiosInterceptor.tsx
  src/components/PageTitle.tsx
  src/components/RouteTitle.tsx
  src/layout/Content.tsx
  src/pages/Branches.tsx
  src/pages/Company.tsx
  src/pages/Dashboard.tsx
  src/pages/Manage/Manage.tsx
  src/pages/NotFound.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/routes/router.tsx
  src/shared/constants/search-contexts.ts
  src/shared/helpers/index.ts
  src/shared/helpers/jwt.helpers.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/helpers/url.helpers.ts
Labels: enhancement

#713 update: Move catalog states to separate slices
  src/__mocks__/store.ts
  src/__mocks__/tests/Header.test.tsx
  src/components/Search/Search.tsx
  src/layout/Header/Header.tsx
  src/pages/Callback.tsx
  src/pages/Company.tsx
  src/pages/Setup/EmployeeSetup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/shared/constants/index.ts
  src/shared/constants/searchContexts.ts
  src/shared/helpers/index.ts
  src/shared/helpers/url.helpers.ts
  src/shared/helpers/userManager.helpers.ts
  src/store/features/appConfigSlice.ts
  src/store/features/branchSlice.ts
  src/store/features/companySlice.ts
  src/store/features/employeeSlice.ts
  src/store/features/index.ts
  src/store/features/setupSlice.ts
  src/store/index.ts
Labels: enhancement

#714 feat: Create sidebar menu, refactor
  src/ClientLoader.tsx
  src/__mocks__/store.ts
  src/__mocks__/tests/Footer.test.tsx
  src/__mocks__/tests/Header.test.tsx
  src/components/Search/Search.tsx
  src/components/Search/StyledSearch.tsx
  src/layout/Footer/components/License.tsx
  src/layout/Footer/index.ts
  src/layout/Header/Header.tsx
  src/layout/Header/index.ts
  src/layout/Sidebar/SideBar.tsx
  src/layout/Sidebar/components/Menu.tsx
  src/layout/Sidebar/index.ts
  src/pages/Employees.tsx
  src/pages/Setup/BranchSetup.tsx
  src/pages/Setup/CompanySetup.tsx
  src/pages/Setup/EmployeeSetup.tsx
  src/pages/Setup/Setup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/routes/router.tsx
  src/shared/constants/configs.ts
  src/shared/constants/index.ts
  src/shared/constants/menu-items.ts
  src/shared/constants/routes.ts
  src/shared/constants/search-contexts.ts
  src/shared/constants/urls.ts
  src/shared/helpers/index.ts
  src/shared/helpers/user-manager.helpers.ts
  src/shared/models/route.ts
  src/shared/models/setup.ts
  src/store/features/appConfigSlice.ts
  src/store/features/branchSlice.ts
  src/store/features/companySlice.ts
  src/store/features/employeeSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#715 feat: Init Employees table
  src/components/UI/Table/Table.tsx
  src/components/UI/Table/index.ts
  src/components/UI/Table/table.model.ts
  src/layout/Footer/Footer.tsx
  src/layout/Footer/components/License.tsx
  src/pages/Employees.tsx
  src/pages/Manage/Employee/Employee.tsx
  src/pages/Manage/Employee/pages/CreateEditEmployee.tsx
  src/pages/Manage/Employee/pages/EmployeeList.tsx
  src/routes/router.tsx
  src/shared/constants/employee.ts
  src/shared/constants/index.ts
  src/shared/constants/routes.ts
  src/shared/constants/search-contexts.ts
  src/shared/helpers/url.helpers.ts
  src/shared/models/route.ts
Labels: enhancement

#716 feat: Init company license, table pagination
  src/AxiosInterceptor.tsx
  src/ClientLoader.tsx
  src/__mocks__/store.ts
  src/__mocks__/tests/Footer.test.tsx
  src/components/UI/Page/Page.tsx
  src/components/UI/Page/PageSubtitle.tsx
  src/components/UI/Page/PageTitle.tsx
  src/components/UI/Page/index.ts
  src/components/UI/Table/Table.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Footer/components/Environment.tsx
  src/pages/Branches.tsx
  src/pages/Company.tsx
  src/pages/Dashboard.tsx
  src/pages/Manage/Employee/pages/CreateEditEmployee.tsx
  src/pages/Manage/Employee/pages/EmployeeList.tsx
  src/pages/Manage/Manage.tsx
  src/pages/NotFound.tsx
  src/pages/Setup/BranchSetup.tsx
  src/pages/Setup/components/CompanyDetailsForm.tsx
  src/pages/Setup/components/EmployeeDetailsForm.tsx
  src/shared/configs/axios.ts
  src/shared/configs/theme.ts
  src/shared/constants/configs.ts
  src/shared/constants/urls.ts
  src/shared/models/index.ts
  src/shared/models/license.ts
  src/store/features/branchSlice.ts
  src/store/features/companySlice.ts
  src/store/features/employeeSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/licenseSlice.ts
  src/store/index.ts
Labels: enhancement

#717 feat: Init branch pages
  src/components/UI/Table/Table.tsx
  src/components/UI/Table/table.model.ts
  src/pages/Branches.tsx
  src/pages/Manage/Branch/Branch.tsx
  src/pages/Manage/Branch/pages/BranchTable.tsx
  src/pages/Manage/Branch/pages/CreateEditBranch.tsx
  src/pages/Manage/Employee/pages/EmployeeTable.tsx
  src/routes/router.tsx
  src/shared/constants/branches.ts
  src/shared/constants/configs.ts
  src/shared/constants/employees.ts
  src/shared/constants/index.ts
  src/shared/constants/routes.ts
  src/shared/models/response.ts
  src/shared/models/route.ts
  src/store/features/branchSlice.ts
  src/store/features/employeeSlice.ts
  src/store/features/setupSlice.ts
Labels: enhancement

#718 feat: Create table layout
  src/components/UI/Loader.tsx
  src/components/UI/Page/PageTitle.tsx
  src/components/UI/Table/Table.tsx
  src/components/UI/Table/table.model.ts
  src/layout/Header/Header.tsx
  src/pages/Manage/Branch/pages/BranchTable.tsx
  src/pages/Manage/Branch/pages/CreateEditBranch.tsx
  src/pages/Manage/Employee/pages/CreateEditEmployee.tsx
  src/pages/Manage/Employee/pages/EmployeeTable.tsx
  src/pages/Manage/Manage.tsx
  src/pages/Manage/components/TableLayout.tsx
  src/shared/constants/configs.ts
Labels: enhancement

#720 feat: Parse data manually
  .eslintrc.json
  package-lock.json
  src/AxiosInterceptor.tsx
  src/ClientLoader.tsx
  src/components/UI/Table/StyledTable.tsx
  src/components/UI/Table/Table.tsx
  src/components/UI/Table/table.model.ts
  src/pages/Manage/Branch/pages/BranchTable.tsx
  src/pages/Manage/Branch/pages/CreateEditBranch.tsx
  src/pages/Manage/Branch/pages/components/BrachDetailsForm.tsx
  src/pages/Manage/Employee/pages/CreateEditEmployee.tsx
  src/pages/Manage/Employee/pages/EmployeeTable.tsx
  src/pages/Setup/BranchSetup.tsx
  src/pages/Setup/EmployeeSetup.tsx
  src/routes/router.tsx
  src/shared/configs/axios.ts
  src/shared/constants/configs.ts
  src/shared/constants/routes.ts
  src/shared/helpers/data.helpers.ts
  src/shared/helpers/index.ts
  src/shared/models/branch.ts
  src/shared/models/company.ts
  src/shared/models/employee.ts
  src/shared/models/route.ts
  src/store/features/branchSlice.ts
  src/store/features/employeeSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/setupSlice.ts
  src/store/index.ts
Labels: enhancement

#721 Re-Enable Dependabot for NPM
  .github/dependabot.yml
Labels: enhancement, maintenance

#733 fix: Delete branch issues
  src/components/UI/Table/StyledTable.tsx
  src/components/UI/Table/Table.tsx
  src/layout/Header/Header.tsx
  src/pages/Manage/Branch/pages/BranchTable.tsx
  src/pages/Manage/Employee/pages/EmployeeTable.tsx
  src/pages/Setup/EmployeeSetup.tsx
  src/shared/constants/menu-items.ts
  src/store/features/employeeSlice.ts
Labels: bug

#735 feat: Load pages lazyly
  src/components/AdminRoute.tsx
  src/pages/Callback.tsx
  src/pages/Manage/Branch/pages/CreateEditBranch.tsx
  src/pages/Manage/Branch/pages/components/BrachDetailsForm.tsx
  src/routes/lazy-load.tsx
  src/routes/router.tsx
  src/store/features/authSlice.ts
Labels: enhancement

#736 feat: Edit branch
  src/components/UI/Table/Table.tsx
  src/pages/Manage/Branch/pages/BranchTable.tsx
  src/pages/Manage/Branch/pages/CreateEditBranch.tsx
  src/pages/Manage/Branch/pages/components/BrachDetailsForm.tsx
  src/pages/Protected.tsx
  src/routes/lazy-loaded-component.tsx
  src/routes/router.tsx
  src/shared/constants/configs.ts
  src/shared/constants/routes.ts
  src/shared/models/route.ts
  src/store/features/branchSlice.ts
Labels: enhancement
