Repository fossa-app/UI, pull requests merged in 2024-09, with the labels that each got.

#639 Fix via Super Linter
  Dockerfile
  README.md
  lint.ps1
  src/App.css
  src/index.css
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: documentation, maintenance

#640 feat: init eslint
  .build.ps1
  .eslintrc.json
  .husky/pre-commit
  .prettierrc
  .super-linter.yml
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.css
  src/App.scss
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.scss
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
  src/setupTests.ts
Labels: enhancement, maintenance

#641 Fix Linting Errors
  .eslintrc.json
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cicd.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .husky/pre-commit
  package-lock.json
  package.json
  public/index.html
  src/App.scss
  src/App.tsx
Labels: maintenance

#650 Set port for dev
  README.md
  start.ps1
Labels: documentation, enhancement

#651 Fix deployment
  .github/workflows/cicd.yml
  .github/workflows/lint.yml
Labels: enhancement, maintenance

#652 Fix health check
  Dockerfile
Labels: bug

#665 Update CURL package version
  Dockerfile
Labels: maintenance

#661 feat: api integration
  jest.config.ts
  package-lock.json
  package.json
  src/App.tsx
  src/AxiosInterceptor.tsx
  src/core/axios.ts
  src/index.tsx
  src/shared/constants/index.ts
  src/shared/constants/urls.ts
  src/shared/helpers/index.ts
  src/shared/helpers/url.helpers.ts
  src/shared/models/client.ts
  src/shared/models/index.ts
  tsconfig.json
Labels: enhancement

#667 feat: init fusion auth
  .eslintrc.json
  jest.config.ts
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/__mocks__/fusionauth-mock.ts
  src/index.tsx
  src/pages/Content.tsx
  src/pages/Dashboard.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/shared/constants/index.ts
  src/shared/constants/routes.ts
  src/shared/models/index.ts
  src/shared/models/route.ts
  tsconfig.json
Labels: enhancement

#668 Disable Dependabot for NPM
  .github/dependabot.yml
Labels: maintenance

#669 feat: set client id
  src/FusionAuthConfigLoader.tsx
  src/index.tsx
  src/pages/Dashboard.tsx
  src/pages/Login.tsx
  src/shared/constants/configs.ts
  src/shared/constants/index.ts
Labels: enhancement

#670 feat: init redux
  jest.config.ts
  package-lock.json
  package.json
  src/FusionAuthConfigLoader.tsx
  src/index.tsx
  src/store/features/clientSlice.ts
  src/store/features/index.ts
  src/store/index.ts
Labels: enhancement

#671 Replace Hardcoded URLs
  src/FusionAuthConfigLoader.tsx
  src/shared/constants/configs.ts
Labels: bug

#672 feat: create config feature
  src/FusionAuthConfigLoader.tsx
  src/shared/constants/configs.ts
  src/shared/models/error.ts
  src/shared/models/index.ts
  src/shared/models/status.ts
  src/store/features/clientSlice.ts
  src/store/features/configSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/index.ts
  src/store/index.ts
Labels: enhancement

#673 Downgrade curl
  Dockerfile
Labels: bug

#674 feat: init license
  .prettierrc
  jest.config.ts
  package-lock.json
  package.json
  src/App.tsx
  src/FusionAuthConfigLoader.tsx
  src/__mocks__/store.ts
  src/core/axios.ts
  src/layout/Content.tsx
  src/layout/Footer/Footer.tsx
  src/layout/Footer/components/Environment.tsx
  src/layout/Footer/components/License.tsx
  src/layout/Header.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/shared/constants/urls.ts
  src/shared/models/index.ts
  src/shared/models/system.ts
  src/store/features/configSlice.ts
  src/store/features/identitySlice.ts
  src/store/features/index.ts
  src/store/features/licenseSlice.ts
  src/store/index.ts
Labels: enhancement

#675 feat: init mui theme
  src/FusionAuthConfigLoader.tsx
  src/core/theme.config.ts
  src/layout/Footer/Footer.tsx
  src/layout/Header.tsx
  src/pages/Login.tsx
  src/shared/constants/colors.ts
  src/shared/constants/index.ts
  src/store/features/configSlice.ts
  src/store/features/identitySlice.ts
Labels: enhancement

#677 fix: fix Environment component
  src/App.test.tsx
  src/__mocks__/store.ts
  src/__mocks__/tests/Footer.test.tsx
  src/__mocks__/tests/Header.test.tsx
  src/layout/Footer/components/Environment.tsx
  src/layout/Header.tsx
  src/shared/models/common.ts
  src/shared/models/index.ts
Labels: bug

#678 feat: Init login flow
  src/FusionAuthConfigLoader.tsx
  src/layout/Footer/components/Environment.tsx
  src/layout/Footer/components/License.tsx
  src/layout/Header.tsx
  src/shared/constants/configs.ts
  src/store/features/identitySlice.ts
Labels: enhancement

#679 feat(Header.tsx): Init logout
  src/layout/Header.tsx
Labels: enhancement

#680 feat: Add logo and unit tests
  src/__mocks__/fusionauth-mock.ts
  src/__mocks__/store.ts
  src/__mocks__/tests/Footer.test.tsx
  src/__mocks__/tests/Header.test.tsx
  src/__mocks__/tests/Login.test.tsx
  src/layout/Header.tsx
  src/pages/Login.tsx
  src/shared/components/icons/Logo.tsx
Labels: enhancement

#681 feat: Create UserMenu component
  src/App.tsx
  src/__mocks__/tests/Header.test.tsx
  src/layout/Header/Header.tsx
  src/layout/Header/components/UserMenu/UserMenu.tsx
Labels: enhancement

#682 update: Minor improvements
  src/core/theme.config.ts
  src/layout/Footer/components/Environment.tsx
  src/layout/Footer/components/License.tsx
  src/pages/Login.tsx
  src/shared/constants/colors.ts
  src/shared/helpers/url.helpers.ts
Labels: enhancement

#685 feat: Init authorization
  src/AxiosInterceptor.tsx
  src/pages/Home.tsx
  src/shared/constants/configs.ts
  src/shared/helpers/index.ts
  src/shared/helpers/storage.helpers.ts
  src/shared/helpers/user.helpers.ts
  src/shared/models/common.ts
  src/shared/models/index.ts
  src/shared/models/user.ts
  src/store/features/authSlice.ts
  src/store/features/identitySlice.ts
Labels: enhancement

#687 update: Change page names
  src/App.tsx
  src/__mocks__/tests/Login.test.tsx
  src/pages/Callback.tsx
  src/pages/Company.tsx
  src/pages/Dashboard.tsx
  src/pages/Login.tsx
  src/pages/Protected.tsx
Labels: enhancement
